services:
  gateway-blue:
    image: ${GATEWAY_BLUE_IMAGE}

  gateway-green:
    image: ${GATEWAY_GREEN_IMAGE}

  nginx:
    image: ${NGINX_IMAGE}

  certbot:
    image: ${CERTBOT_IMAGE}

  migrations:
    image: ${MIGRATIONS_IMAGE}