services:
  gateway:
    image: ghcr.io/kpa9pt/repair-crm-gateway:latest

  migrations:
    image: ghcr.io/kpa9pt/repair-crm-migrations:latest

  nginx:
    image: ghcr.io/kpa9pt/repair-crm-nginx:latest

  certbot:
    image: ghcr.io/kpa9pt/repair-crm-certbot:latest