services:
  postgres:
    ports:
      - "5432:5432"   # только для тестов локально
  rabbitmq:
    ports:
      - "5672:5672"
volumes:
  postgres_data:
    external: false   # ← переопределяем для тестов

#  gateway:
#    environment:
#      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/repair_crm_test
#
#  migrations:
#    environment:
#      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/repair_crm_test