services:
  postgres:
    ports:
      - "5432:5432"   # только для тестов локально

#  gateway:
#    environment:
#      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/repair_crm_test
#
#  migrations:
#    environment:
#      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/repair_crm_test